### ISSUE TITLE
can u help with worldtoscreen function on my external

### ISSUE THREAD

**Issue by tihomirocrew** [wildangelcult/samp-hack#1]
send ur discord pls

**Comment by wildangelcult** [comment]
rengaf09

29. 6. 2023 11:09, 11:09, wigyware ***@***.***> napsal/a:

**Comment by wildangelcult** [comment]
Send me an email
admin@wildangelcult.com

**Comment by tihomirocrew** [comment]
i have my external aimbot
`
void move_cursor(int x, int y) {
    INPUT input;
    input.type = INPUT_MOUSE;
    input.mi.dx = x * (65536 / resolution.x);
    input.mi.dy = y * (65536 / resolution.y);
    input.mi.mouseData = 0;
    input.mi.dwFlags = MOUSEEVENTF_MOVE | MOUSEEVENTF_ABSOLUTE;
    input.mi.time = 0;
    input.mi.dwExtraInfo = 0;

    SendInput(1, &input, sizeof(INPUT));
}

void aim_thread() {
    while (TRUE) {
        Sleep(10);
        if (is_window_active(target_hwnd)) {
            if (vars::aimbot) {
                uintptr_t ped = memory::read<uintptr_t>(0xB6F5F0);

                uintptr_t ped_matrix = memory::read<uintptr_t>(ped + 0x14);
                vec3 pedpos =
                { memory::read<float>(ped_matrix + 0x30),
                  memory::read<float>(ped_matrix + 0x34),
                  memory::read<float>(ped_matrix + 0x38) };

                vec2 camerapos =
                { memory::read<float>(0xB6F9CC),
                  memory::read<float>(0xB6F9D0) };

                uintptr_t target = memory::read<uintptr_t>(ped + 0x79C);

                if (target > 0) {
                    uintptr_t target_matrix = memory::read<uintptr_t>(target + 0x14);
                    vec3 targetpos =
                    { memory::read<float>(target_matrix + 0x30),
                      memory::read<float>(target_matrix + 0x34),
                      memory::read<float>(target_matrix + 0x38) };

                    float target_hp = memory::read<float>(target + 0x540);
                    if (target_hp > 0) {
                        float aa = fabs(camerapos.x - targetpos.x);
                        float ab = fabs(camerapos.y - targetpos.y);
                        float ac = sqrt(aa * aa + ab * ab);
                        float alpha = asin(aa / ac);
                        float beta = acos(aa / ac);

                        if ((pedpos.x > targetpos.x) && (pedpos.y < targetpos.y)) { beta = -beta; }             //1 part
                        if ((pedpos.x > targetpos.x) && (pedpos.y > targetpos.y)) { beta = beta; }              //2 part
                        if ((pedpos.x < targetpos.x) && (pedpos.y > targetpos.y)) { beta = (alpha + (1.5707)); }//3 part
                        if ((pedpos.x < targetpos.x) && (pedpos.y < targetpos.y)) { beta = (-alpha - (1.5707)); }//4 part

                        if (GetAsyncKeyState(VK_RBUTTON) && vars::mode == 1) {
                            std::cout << "target pos on screen: X=" << screen.x << ", Y=" << screen.y << std::endl;
                            move_cursor(screen.x, screen.y);
                            memory::write<float>(0xB6F258, beta + 0.0389);
                        }
                        if (GetAsyncKeyState(VK_LBUTTON) && vars::mode == 2) {
                            std::cout << "target pos on screen: X=" << screen.x << ", Y=" << screen.y << std::endl;
                            move_cursor(screen.x, screen.y);
                            //memory::write<float>(0xB6F258, beta + 0.0389);
                        }
                    }
                }
            }
        }
    }
}
`

**Comment by tihomirocrew** [comment]
i need convert world to screen coords externaly with memory addresses

**Comment by wildangelcult** [comment]
Do your research man, I have not been into game hacking for a while now.

https://guidedhacking.com/threads/world2screen-direct3d-and-opengl-worldtoscreen-functions.8044/
